Repository jupyter-server/synchronizer, pull requests merged in 2022-05, with the labels that each got.

#16 Use flit build backend
  .flake8
  MANIFEST.in
  jupyter_server_synchronizer/__init__.py
  pyproject.toml
  setup.cfg
Labels: maintenance

#17 Add relevant kernel name to persistent kernel storage for rehydration
  Makefile
  jupyter_server_synchronizer/gateway.py
  jupyter_server_synchronizer/kernel_db.py
  jupyter_server_synchronizer/kernel_records.py
  jupyter_server_synchronizer/manager.py
  tests/test_kernel_db.py
Labels: bug

#18 Automated Changelog Entry for 0.0.5 on main
  CHANGELOG.md
Labels: documentation

#19 write only the allowed columns to the database
  jupyter_server_synchronizer/kernel_db.py
Labels: bug

#21 Automated Changelog Entry for 0.0.6 on main
  CHANGELOG.md
Labels: documentation

#22 If synchronizer fails, warn gracefully and continue
  jupyter_server_synchronizer/manager.py
Labels: bug

#24 Automated Changelog Entry for 0.0.7 on main
  CHANGELOG.md
Labels: documentation

#26 Add missing list_sessions method
  jupyter_server_synchronizer/manager.py
Labels: bug

#27 Automated Changelog Entry for 0.0.8 on main
  CHANGELOG.md
Labels: documentation
