Repository jupyter-server/synchronizer, pull requests merged in 2022-04, with the labels that each got.

#2 Add packaging config and CI elements
  .pre-commit-config.yaml
  CHANGELOG.md
  MANIFEST.in
  jupyter-config/jupyter_server_synchronizer.json
  jupyter_server_synchronizer/__init__.py
  jupyter_server_synchronizer/_version.py
  jupyter_server_synchronizer/extension.py
  jupyter_server_synchronizer/kernel_db.py
  jupyter_server_synchronizer/kernel_records.py
  pyproject.toml
  tests/test_kernel_db.py
  tests/test_kernel_records.py
Labels: maintenance

#4 Make "kernel fetching" configurable and client-driven
  CHANGELOG.md
  README.md
  jupyter_server_synchronizer/extension.py
  jupyter_server_synchronizer/handlers.py
  jupyter_server_synchronizer/kernel_records.py
  jupyter_server_synchronizer/traits.py
Labels: enhancement

#5 Automated Changelog Entry for 0.0.2 on main
  CHANGELOG.md
Labels: documentation

#6 Add typing support
  .pre-commit-config.yaml
  jupyter_server_synchronizer/kernel_db.py
  jupyter_server_synchronizer/kernel_records.py
  jupyter_server_synchronizer/py.typed
  pyproject.toml
  tests/test_kernel_records.py
Labels: maintenance

#7 Make Synchronizer work with Jupyter Kernel Gateways out-of-the-box
  MANIFEST.in
  Makefile
  README.md
  jupyter_server_synchronizer/extension.py
  jupyter_server_synchronizer/gateway.py
Labels: enhancement

#8 Automated Changelog Entry for 0.0.3 on main
  CHANGELOG.md
Labels: documentation

#11 Synchronizing before the server starts should be configurable.
  jupyter_server_synchronizer/extension.py
Labels: enhancement

#13 Synchronizer as a session manager
  README.md
  jupyter-config/jupyter_server_synchronizer.json
  jupyter_server_synchronizer/__init__.py
  jupyter_server_synchronizer/gateway.py
  jupyter_server_synchronizer/handlers.py
  jupyter_server_synchronizer/manager.py
  setup.cfg
Labels: enhancement

#14 Automated Changelog Entry for 0.0.4 on main
  CHANGELOG.md
Labels: documentation
